### ISSUE TITLE
Ошибка 415 при запуске тестов

### ISSUE THREAD

**Issue by bigman212** [qwertukg/demo#1]
В чем может быть ошибка при запуске тестов? На 2 и 3 тестах выдает ошибку 415. Ваш код не менял.

**Comment by qwertukg** [comment]
> В чем может быть ошибка при запуске тестов?

Попробуйте сделать запрос вручную, и посмотреть ответ.

**Comment by bigman212** [comment]
При запуске без тестов всё работает нормально. Только возникла проблема сохранения данных в бд. При ручном сохранении (с использовании repository.save в DemoApplication) сохраняет объект только на время сессии. 
И еще вопрос - как вручную организовать POST запрос? Я так понял метод с передачей параметров в url не работает. Тогда как?
Спасибо за ответы. Очень хотелось бы разобраться во всей этой теме на примере вашего простого и понятного приложения.

**Comment by qwertukg** [comment]
По поводу БД не могу сказать почему вас так - смотрите сервер БД, ну или скиньте описание своего окружения сюда - попробуем разобраться

> Я так понял метод с передачей параметров в url не работает

`http://example.com?param-name=value1`
```kotlin
fun create(@RequestParam(value = "param-name", required = false) param: String) {
    print(param) // value1
}
```
